# Generated by Django 4.1.7 on 2023-02-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculine'), ('Feminino', 'Feminine'), ('Outro', 'Other')], default='Outro', max_length=20),
        ),
    ]
