# Generated by Django 4.1.7 on 2023-02-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('diretor(a)', 'Director'), ('psicólogo(a)', 'Psychologist'), ('instrutor(a) de ensino', 'Teaching Instructor'), ('monitor(a) de ensino', 'Teaching Monitor'), ('secretário(a)', 'Secretary'), ('outros', 'Other')], default='outros', max_length=50),
        ),
    ]
