# Generated by Django 4.1.7 on 2023-02-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users',
            new_name='instructors',
        ),
    ]
