# Generated by Django 4.1.7 on 2023-02-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
