# Generated by Django 4.1.7 on 2023-02-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='branch',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
