# Generated by Django 4.1.7 on 2023-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
